name: AI review

on:
  workflow_dispatch:
    inputs:
      review-command:
        type: choice
        default: "run"
        options:
          - run
          - run-inline
          - run-context
          - run-summary
          - run-inline-reply
          - run-summary-reply
          - clear-inline
          - clear-summary
        required: true
        description: "Review command (https://github.com/Nikita-Filonov/ai-review/tree/main/docs/cli#-available-commands)"

      pull-request-number:
        type: string
        required: true
        description: "Pull Request number to review"

permissions:
  pull-requests: write # Write comments 
  contents: read # Read contents of pull request and whole repository for context

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: Nikita-Filonov/ai-review@v0.77.0
        with:
          review-command: ${{ inputs.review-command }}
        env:
          LLM__PROVIDER: "OPENROUTER"
          LLM__META__MODEL: "openai/gpt-5.6-luna"
          LLM__META__TEMPERATURE: "0.3"
          LLM__HTTP_CLIENT__API_URL: "https://openrouter.ai/api/v1"
          LLM__HTTP_CLIENT__API_TOKEN: ${{ secrets.OPENROUTER_API_KEY }}

          VCS__PROVIDER: "GITHUB"
          VCS__PIPELINE__OWNER: ${{ github.repository_owner }}
          VCS__PIPELINE__REPO: ${{ github.event.repository.name }}
          VCS__PIPELINE__PULL_NUMBER: ${{ inputs.pull-request-number }}
          VCS__HTTP_CLIENT__API_URL: "https://api.github.com"
          VCS__HTTP_CLIENT__API_TOKEN: ${{ secrets.GITHUB_TOKEN }}