name: Dockerfile linting

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - Dockerfile
      - '.github/workflows/docker-ci.yml'
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - '.github/workflows/docker-ci.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Hadolint linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: 'Dockerfile'
          failure-threshold: style
