name: PR linting

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

on:
  pull_request_target:  # zizmor: ignore[dangerous-triggers] No read permission granted
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  pr-check:
    name: Validate PR title
    runs-on: ubuntu-slim
    permissions:
      pull-requests: read  # Lints PR title, description, etc
    steps:
      - uses: amannn/action-semantic-pull-request@v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
