name: Linting and tests for python projects

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions:
  contents: read
  code-quality: write

env: # Keep in sync with dockerfile
  PYTHON_VERSION: ">=3.14"
  POETRY_VERSION: "2.4.1"

jobs:
  ruff:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - run: "pipx install poetry==${{POETRY_VERSION}}"
      - uses: actions/setup-python@v7
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: "poetry"
      - uses: actions/cache@v6
        with:
          path: .ruff_cache
          key: ${{ runner.os }}-ruff-${{ hashFiles('pyproject.toml', 'poetry.lock') }}
      - run: "poetry install"
      - run: "poetry run ruff check"
  mypy:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - run: "pipx install poetry==${{POETRY_VERSION}}"
      - uses: actions/setup-python@v7
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: "poetry"
      - uses: actions/cache@v6
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-mypy-${{ hashFiles('pyproject.toml', 'poetry.lock') }}
      - run: "poetry install"
      - run: "poetry run mypy src tests"
  pytest:
    needs: [ ruff, mypy ]
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - run: "pipx install poetry==${{POETRY_VERSION}}"
      - uses: actions/setup-python@v7
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: "poetry"
      - uses: actions/cache@v6
        with:
          path: .pytest_cache
          key: ${{ runner.os }}-mypy-${{ hashFiles('pyproject.toml', 'poetry.lock') }}
      - run: "poetry install"
      - run: "poetry run pytest --cov=src --cov-report=xml"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
