name: Linting and tests for python projects

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions: read-all

env:
  PYTHON_VERSION: "3.14"
  POETRY_VERSION: "2.4"


jobs:
  ruff:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: ${PYTHON_VERSION}
          cache: "poetry"
      - run: "pipx install poetry"
      - run: "poetry run ruff check"
